---
title: "Apresentação IPCA"
author: "CODEPLAN"
date: "9 de abril de 2019"
output: 
  powerpoint_presentation:
    reference_doc: ipca.pptx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F)
```

```{r graf geral}

library(ggplot2)

p <- theme(title = element_text(size = 15, face = "bold"),
           legend.text = element_text(size = 15))

```

```{r ipca_rms, dpi = 300,  fig.height=9, fig.width=13}

library(sidrar)
library(tidyverse)
library(lubridate)
library(ggrepel)
library(scales)
library(gridExtra)

dados_graf_1 <- sidrar::get_sidra(api = "/t/1419/n1/all/n7/all/n6/all/v/63,69/p/last%201/c315/7169/d/v63%202,v69%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil, Região Metropolitana e Município`,
                Variável,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor)

refs <- tibble(ref_df = dados_graf_1 %>% dplyr::filter(Variável == "IPCA - Variação mensal",
                                                UF == "Brasília - DF",
                                                Item == "Índice geral") %>% dplyr::select(Valor) %>% c(),
               
               ref_max = dados_graf_1 %>% dplyr::filter(Variável == "IPCA - Variação acumulada no ano",
                                                 Item == "Índice geral") %>%
                 dplyr::select(Valor) %>% max(),
               
               ref_min = dados_graf_1 %>% dplyr::filter(Variável == "IPCA - Variação mensal",
                                                 Item == "Índice geral") %>%
                 dplyr::select(Valor) %>% min())

plot_graf_1 <- dados_graf_1 %>%
  
  dplyr::filter(Variável %in% c("IPCA - Variação acumulada no ano", "IPCA - Variação mensal") & Item == "Índice geral") %>%
  
  dplyr::select(c(Data, UF, Variável, Valor)) %>%
  
  ggplot(aes(x = forcats::fct_reorder2(UF, factor(Variável, 2), Valor), y = Valor)) +
  
  geom_col(aes(fill = factor(UF), alpha = Variável), position = "identity") +
  
  scale_fill_manual(values = c("seagreen3", "seagreen3", "seagreen3",
                               "steelblue2","orange", rep("seagreen3", 12)),
                    guide = F) +
  
  scale_alpha_manual(values = c(0.5, 0.9)) +
  
  theme_minimal() +
  
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust = 0.5,
                                   size = 15,
                                   face = "bold"),
        
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(linetype = "dashed", size = 1),
        panel.grid.minor.y = element_line(linetype = "dashed", size = 1),
        
        legend.position = "bottom") +
  
  labs(x = "", y = "", alpha = "") +
  
  geom_hline(yintercept = 0, size = 1) +
  
  geom_text_repel(aes(label = Valor), size = 5, position = position_dodge(0.9),
            vjust = ifelse(("Valor" <= -0.02), -1, -0.5)) +
  
  ylim(ifelse(refs$ref_min > 0, 0, refs$ref_min-0.5), refs$ref_max+0.5) +
  
  labs(title = "Índice Nacional de Preços ao Consumidor Amplo (IPCA) – Regiões.",
       subtitle = "Variação mensal e acumulado no ano (%).",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.")

plot_graf_1 + p

```

```{r ipca_grupos_mensal, dpi = 300,  fig.height=9, fig.width=13}

dados_graf_2 <- sidrar::get_sidra(api = "/t/1419/n1/all/n6/5300108/v/63/p/last%201/c315/7169,7170,7445,7486,7558,7625,7660,7712,7766,7786/d/v63%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil e Município`,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor)

ordem <- dados_graf_2 %>%
  
  dplyr::filter(UF == "Brasília - DF", Item != "Índice geral") %>%
  
  dplyr::arrange(Valor) %>%
  
  dplyr::select(Item) %>%
  
  dplyr::mutate(Item = stringr::str_remove(Item, "\\d+."))

plot_graf_2 <- dados_graf_2 %>%
  
  dplyr::mutate(Item = stringr::str_remove(Item, "\\d+.")) %>%
  
  dplyr::mutate(Item = factor(Item, levels = c(ordem$Item, "Índice geral"))) %>%
  
  ggplot(aes(y = Valor, x = Item, fill = UF)) +
  
  coord_flip() +
  
  geom_bar(stat = "identity", position = "dodge") + 
  
  theme_light() +
  
  labs(x = "", 
       y = "",
       fill = "") +
  
  theme(panel.grid.major.x = element_line(linetype = "dashed", size = 1),
        panel.grid.minor.x = element_line(linetype = "dashed", size = 1),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text.y = element_text(size = 14),
        
        legend.position = "bottom") +
  
  scale_fill_manual(values = c("dodgerblue2", "darkorange")) +
  
  geom_text(aes(label = Valor), 
            position = position_dodge(0.9),
            hjust = ifelse(("Valor" <= 0), -1, -0.2)) +
  
  labs(title = "IPCA – Geral e Grupos",
       subtitle = "Variação mensal (%).",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.")

plot_graf_2 + p

```

```{r tabela_maiores, dpi = 300}

library(grid)
library(gridExtra)
library(gtable)

dados_tabela_1 <- get_sidra(api = "/t/1419/n1/all/n7/all/n6/all/v/all/p/last%201/c315/all/d/v63%202,v66%204,v69%202,v2265%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil, Região Metropolitana e Município`,
                Variável,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor) %>%

  dplyr::filter(UF == "Brasília - DF",
                Variável %in% c("IPCA - Variação mensal", "IPCA - Peso mensal"),
                stringr::str_detect(Item, stringr::regex("(\\d{7})"))) %>%
  
  tidyr::drop_na() %>%
  
  tidyr::spread(key = Variável, value = Valor) %>%
  
  dplyr::mutate(Contribuição = (`IPCA - Variação mensal`)*(`IPCA - Peso mensal`/100)) %>%
  
  dplyr::arrange(desc(Contribuição)) %>%
  
  dplyr::slice(c(1:5, (n()-4):n())) %>%
  
  dplyr::select(Item, Variação = `IPCA - Variação mensal`, Peso = `IPCA - Peso mensal`, Contribuição) %>%
  
  dplyr::mutate_at(vars(Variação:Contribuição), funs(round(., 2))) %>%
  
  dplyr::mutate(Item = stringr::str_remove(Item, "\\d+."))

tema <- ttheme_minimal(core=list(bg_params = list(fill = c(hsv(0.05, seq(1, 0.2, length.out = 5)),
                                                           hsv(0.35, seq(0.1, 0.5, length.out = 5))), col=NA)))

plot_tabela_1 <- tableGrob(dados_tabela_1, theme = tema, rows = NULL)

table <- plot_tabela_1

grid.newpage()

h <- grobHeight(table)
w <- grobWidth(table)

title <- textGrob("IPCA - maiores e menores contribuições no mês - Brasília", 
                  y = unit(0.5,"npc") + 1*h, 
                  vjust = 0, gp = gpar(fontsize=10, fontface = "bold"))

footnote <- textGrob("Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN", 
                     x = unit(0.5,"npc") - 1*w,
                     y = unit(0.5,"npc") - 1*h, gp = gpar(fontsize = 7, fontface = "bold"))

gt <- gTree(children=gList(table, title, footnote))

grid.draw(gt)

```

```{r ipca_12meses, dpi = 300, fig.height=9, fig.width=13}

dados_graf_3 <- sidrar::get_sidra(api = "/t/1419/n1/all/n6/5300108/v/2265/p/all/c315/7169,7170,7445,7486,7558,7625,7660,7712,7766,7786/d/v2265%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil e Município`,
                Variável,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor) %>%
  
  tidyr::drop_na() %>% 
  
  dplyr::filter(Item == "Índice geral",
                UF %in% c("Brasil", "Brasília - DF")) %>%
  
  dplyr::select(c(Data, UF, Valor)) %>%
  
  tidyr::drop_na() %>%
  
  dplyr::mutate(Inferior = case_when(lubridate::year(Data) %in% 2012:2016 ~ 2.5,
                                     lubridate::year(Data) %in% 2017:2018 ~ 3.0,
                                     lubridate::year(Data) %in% 2019 ~ 2.75),
                
                Superior = case_when(lubridate::year(Data) %in% 2012:2016 ~ 6.5,
                                     lubridate::year(Data) %in% 2017:2018 ~ 6.0,
                                     lubridate::year(Data) %in% 2019 ~ 5.75),
                
                Meta = case_when(lubridate::year(Data) %in% 2012:2018 ~ 4.5,
                                 lubridate::year(Data) %in% 2019 ~ 4.25))

date_lim <- last(dados_graf_3$Data) %m-% months(40)

labs <- dados_graf_3 %>% dplyr::group_by(UF) %>% dplyr::summarise(lab = last(Valor))

plot_graf_3 <- dados_graf_3 %>%
  
  dplyr::filter(Data >= date_lim) %>%
  
  dplyr::group_by(UF) %>%
  
  dplyr::mutate(label = ifelse(Valor %in% tail(Valor, 2), round(Valor, 2), NA)) %>%
  
  ggplot(aes(x = Data, y = Valor, color = UF, label = label)) +
  
  geom_line(lwd = 1.2) +
  
  geom_line(aes(y = Meta), color = "black", linetype = "dotted", lwd = 1) +
  
  geom_line(aes(y = Superior), color = "black", linetype = "dashed", lwd = .7) +
  
  geom_line(aes(y = Inferior), color = "black", linetype = "dashed", lwd = .7) +
  
  scale_color_manual(values = c("steelblue2", "orange")) +
  
  
  scale_y_continuous(breaks = seq(0, 12, 1.5),
                     limits = c(0,12)) +
  
  scale_x_date(date_breaks = "6 month",
               labels = date_format("%b-%y"),
               expand = c(0.04,0)) +
  
  labs(y = "",
       x = "",
       colour = "") +

  theme_minimal() +
  
  theme(legend.position = "bottom", 
        
        legend.text = element_text(size = 11),
        
        axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11),
        
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        
        panel.grid.major.y = element_line(linetype = "dashed", size = 0.5),
        panel.grid.minor.y = element_line(linetype = "dashed", size = 0.5)) +
  
  annotate("text", x = date_lim %m+% months(1), y = 4.8, label = "Meta") +
  
  annotate("text", x = date_lim %m+% months(2), y = 2.8, label = "Limite inferior") +

  annotate("text", x = date_lim %m+% months(2), y = 6.3, label = "Limite superior") +
  
  #annotate("text", x = last(dados_graf_3$Data), y = 2.5, label = as.character(labs$lab[2]), color = "orange") +
  
  #annotate("text", x = last(dados_graf_3$Data), y = 4.5, label = as.character(labs$lab[1]), color = "steelblue2") +
  
  labs(title = "IPCA - variação acumulada em doze meses (%) - Brasil e Brasília.",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.") +
  
  geom_label_repel(show.legend = F)

plot_graf_3 + p

```

```{r ipca_grupos_12m, dpi = 300, fig.height=9, fig.width=13}

dados_graf_4 <- sidrar::get_sidra(api = "/t/1419/n1/all/n6/5300108/v/2265/p/last%201/c315/7169,7170,7445,7486,7558,7625,7660,7712,7766,7786/d/v2265%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil e Município`,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor)

ordem <- dados_graf_4 %>%
  
  dplyr::filter(UF == "Brasília - DF", Item != "Índice geral") %>%
  
  dplyr::arrange(Valor) %>%
  
  dplyr::select(Item) %>%
  
  dplyr::mutate(Item = stringr::str_remove(Item, "\\d+."))

plot_graf_4 <- dados_graf_4 %>%
  
  dplyr::mutate(Item = stringr::str_remove(Item, "\\d+."),
                
                Item = factor(Item, levels = c(ordem$Item, "Índice geral"))) %>%
  
  ggplot(aes(y = Valor, x = Item, fill = UF)) +
  
  coord_flip() +
  
  geom_bar(stat = "identity", position = "dodge") + 
  
  theme_light() +
  
  labs(x = "", 
       y = "",
       fill = "") +
  
  theme(panel.grid.major.x = element_line(linetype = "dashed", size = 1),
        panel.grid.minor.x = element_line(linetype = "dashed", size = 1),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text.y = element_text(size = 14),
        
        legend.position = "bottom") +
  
  scale_fill_manual(values = c("dodgerblue2", "darkorange")) +
  
  geom_text(aes(label = Valor), 
            position = position_dodge(0.9),
            hjust = ifelse(("Valor" <= 0), -2, -0.2)) +
  
  labs(title = "IPCA: Índice geral e grupos – Brasil e Brasília.",
       subtitle = "Variação acumulada em 12 meses (%).",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.")

plot_graf_4 + p

```

```{r ipca_gasolina, dpi = 300, fig.height=9, fig.width=13}

dados_graf_5 <- sidrar::get_sidra(api = "/t/1419/n1/all/n6/5300108/v/2265/p/last%2018/c315/7657/d/v2265%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil e Município`,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor) %>%
  
  dplyr::group_by(UF) %>%
  
  dplyr::mutate(label = ifelse(Valor %in% tail(Valor, 2), round(Valor, 2), NA))

plot_graf_5 <- dados_graf_5 %>%
  
  ggplot(aes(x = Data, y = Valor, color = UF, label = label)) + 
  
  geom_line(lwd = 1.2) +
  
  scale_color_manual(values = c("steelblue2", "orange")) +
   
  theme_minimal() +
  
  theme(legend.position = "bottom", 
        
        legend.text = element_text(size = 11),
        
        axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11)) +
        
        #panel.grid.major.x = element_blank(),
        #panel.grid.minor.x = element_blank(),
        
        #panel.grid.major.y = element_line(linetype = "dashed", size = 0.5),
        #panel.grid.minor.y = element_line(linetype = "dashed", size = 0.5)) +
  
  labs(x = "", y = "", color = "") +
  
  labs(title = "IPCA – Gasolina – Brasil e Brasília.",
       subtitle = "Variação acumulada em 12 meses (%).",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.") +
  
  scale_x_date(date_breaks = "1 month",
               labels = date_format("%b-%y")) +
  
  geom_label_repel(show.legend = F)
  
plot_graf_5 + p

```

```{r ipca_bc, dpi = 300, fig.height=9, fig.width=13}

source("C:\\Users\\36277\\Desktop\\acumular.R", encoding = "UTF-8")

aereo <- c("5101010.Passagem aérea")

serv_labs <- c("12.Alimentação fora do domicílio",
               
               "2101001.Aluguel residencial",
               "2101002.Condomínio",
               "2103042.Mão-de-obra",
               
               "33.Consertos e manutenção",
               
               
               "5101026.Transporte escolar",
               "5102005.Seguro voluntário de veículo",
               "5102011.Conserto de automóvel",
               "5102037.Pintura de veículo",
               
               "6201.Serviços médicos e dentários",
               "6202.Serviços laboratoriais e hospitalares",
               
               "7101.Serviços pessoais",
               "7201001.Cinema",
               "7201018.Tratamento de animais",
               "7201052.Locação de DVD",
               "7201054.Boate e danceteria",
               "7201090.Hotel",
               "7201095.Excursão",
               "7203003.Revelação e cópia",
               
               "8101.Cursos regulares",
               "8104.Cursos diversos",
               
               "9101008.Telefone celular",
               "9101022.TV por assinatura com internet",
               "9101021.Telefone com internet - pacote",
               "9101018.Acesso à internet")

prod_ind_labs <- c("3101.Mobiliário",
                   "3201001.Refrigerador", "3201002.Ar-condicionado", "3201006.Máquina de lavar roupa",
                   "3201021.Fogão", "3201050.Chuveiro elétrico", "3201065.Forno de micro-ondas",
                   "3202.TV, som e informática", "43.Joias e bijuterias",
                   "5102001.Automóvel novo", "5102020.Automóvel usado",
                   "5102053.Motocicleta",
                   "6102002.Armação de óculos",
                   "6102011.Lentes de óculos e de contato",
                   "7201010.Instrumento musical",
                   "7201019.Bicicleta",
                   "7203001.Máquina fotográfica",
                   "9101019.Aparelho telefônico",
                   
                   "3102005.Tapete", "3102006.Cortina", "3102007.Utensílios de metal",
                   "3102009.Utensílios de vidro e louça", "3102010.Utensílios de plástico",
                   "3102040.Utensílios diversos",
                   "3103.Cama, mesa e banho",
                   "3201012.Liquidificador",
                   "3201013.Ventilador",
                   "41.Roupas", "42.Calçados e acessórios",
                   "44.Tecidos e armarinho",
                   "5102009.Acessórios e peças",
                   "5102010.Pneu",
                   "6102003.Óculos sem grau",
                   "6201005.Aparelho ortodôntico",
                   "6201006.Artigos ortopédicos",
                   
                   "2103005.Ferragens", "2103008.Material de eletricidade", "2103009.Material de pintura",
                   "2103012.Vidro", "2103014.Tinta", "2103032.Revestimento de piso e parede",
                   "2103039.Cimento", "2103040.Tijolo", "2103041.Material hidráulico", "2103048.Areia",
                   
                   "2104.Artigos de limpeza", "2201003.Carvão vegetal", "3102035.Flores naturais",
                   "5102007.Óleo lubrificante", "5104002.Etanol",
                   "6301.Higiene pessoal",
                   "7201020.Alimento para animais",
                   "7202041.Cigarro",
                   "8102004.Revista", "8102002.Assinatura de jornal", "8102001.Jornal diário",
                   "8103014.Artigos de papelaria", "8103001.Caderno")

monitorados_labs <- c("2202003.Energia elétrica residencial", "2101004.Taxa de água e esgoto",
                      "2201004.Gás de botijão", "2201005.Gás encanado",
                      
                      "6203001.Plano de saúde", "6101001.Anti-infeccioso e antibiótico",
                      "6101002.Analgésico e antitérmico", "6101003.Anti-inflamatório e antirreumático",
                      "6101004.Antigripal e antitussígeno", "6101006.Dermatológico",
                      "6101007.Antialérgico e broncodilatador", "6101009.Gastroprotetor",
                      "6101010.Vitamina e fortificante", "6101011.Hormônio", "6101013.Psicotrópico e anorexígeno",
                      "6101014.Hipotensor e hipocolesterolêmico", "6101051.Oftalmológico",
                      
                      "7201063.Jogos de azar",
                      
                      "5101001.Ônibus urbano", "5101006.Ônibus intermunicipal",
                      "5101007.Ônibus interestadual", "5101004.Trem", "5101011.Metrô",
                      "5101002.Táxi", "5101022.Transporte hidroviário", "5102006.Multa",
                      "5102004.Emplacamento e licença", "5102015.Pedágio", "5104003.Óleo diesel",
                      "5104001.Gasolina", "5104005.Gás veicular",
                      
                      "9101002.Telefone fixo", "9101003.Telefone público", "9101001.Correio")

dados_graf_6 <- sidrar::get_sidra(api = "/t/1419/n6/5300108/v/63,66/p/all/c315/all/d/v63%202,v66%204") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = Município,
                Variável,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor) %>%
  
  dplyr::mutate(Categoria = case_when(Item %in% monitorados_labs ~ "Monitorados",
                                      Item %in% serv_labs ~ "Serviços (s/ Passagem aérea)",
                                      Item %in% prod_ind_labs ~ "Produtos industriais",
                                      Item == "11.Alimentação no domicílio" ~ "Alimentação no domicílio",
                                      Item == "5101010.Passagem aérea" ~ "Passagem aérea")) %>%
  
  dplyr::filter(!is.na(Categoria)) %>%
  
  tidyr::spread(key = Variável, value = Valor) %>%
  
  dplyr::mutate(IPCA = (`IPCA - Variação mensal`)*(`IPCA - Peso mensal`)/100) %>%
  
  dplyr::group_by(Data, Categoria) %>%
  
  dplyr::summarise(IPCA = sum(IPCA, na.rm = T)) %>%
  
  dplyr::ungroup() %>%
  
  tidyr::spread(key = Categoria, value = IPCA) %>%
  
  dplyr::mutate_at(vars(-Data), funs(c(rep(NA, 11), acum(., n = 12)))) %>%
  
  tidyr::drop_na()

date_lim_2 <- last(dados_graf_6$Data) %m-% months(18)

plot_graf_6 <- dados_graf_6 %>%
  
  dplyr::filter(Data >= date_lim_2) %>%
  
  dplyr::select(-`Passagem aérea`) %>%
  
  tidyr::gather(key = Categoria, value = Valor, -Data) %>%
  
  dplyr::group_by(Categoria) %>%
  
  dplyr::mutate(label = ifelse(Valor %in% tail(Valor, 2), round(Valor, 2), NA)) %>%
  
  dplyr::ungroup() %>%
  
  ggplot(aes(x = Data, y = Valor, color = Categoria, label = label)) +
  
  geom_line(lwd = 1) +
  
  theme_light() +
  
  labs(x = "", 
       y = "",
       color = "") +
  
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 90, size = 12, face = "bold"),
        legend.text = element_text(size = 12)) +
  
  scale_x_date(date_labels = "%b-%Y",
               date_breaks = "1 month") +
  
  geom_label_repel(show.legend = F) +
  
  geom_hline(yintercept = 0, lwd = 1) +
  
   labs(title = "IPCA – Categorias BC - Brasília.",
       subtitle = "Contribuição em 12 meses (p.p).",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.")

plot_graf_6 + p

```

```{r ipca_mas, fig.height=9, fig.width=13, dpi = 300}

source("C:\\Users\\36277\\Desktop\\nucleo_mas.R", encoding = "UTF-8")

ipca_mas()

plot_graf_7 + 
  
  labs(title = "IPCA e Núcleo por média aparadada suavizada.",
       subtitle = "Variação acumulada em 12 meses (%).",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.") + p

```

```{r inpc_rms, fig.height=9, fig.width=13, dpi = 300}

dados_graf_8 <- sidrar::get_sidra(api = "/t/1100/n1/all/n7/all/n6/all/v/all/p/last%201/c315/all/d/v44%202,v45%204") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil, Região Metropolitana e Município`,
                Variável,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor)

refs <- tibble(ref_df = dados_graf_8 %>% dplyr::filter(Variável == "INPC - Variação mensal",
                                                       UF == "Brasília - DF",
                                                       Item == "Índice geral") %>% dplyr::select(Valor) %>% c(),
               
               ref_max = dados_graf_8 %>% dplyr::filter(Variável == "INPC - Variação acumulada no ano",
                                                        Item == "Índice geral") %>%
                 dplyr::select(Valor) %>% max(),
               
               ref_min = dados_graf_8 %>% dplyr::filter(Variável == "INPC - Variação mensal",
                                                        Item == "Índice geral") %>%
                 dplyr::select(Valor) %>% min())

plot_graf_8 <- dados_graf_8 %>%
  
  dplyr::filter(Variável %in% c("INPC - Variação acumulada no ano", "INPC - Variação mensal") & Item == "Índice geral") %>%
  
  dplyr::select(c(Data, UF, Variável, Valor)) %>%
  
  ggplot(aes(x = forcats::fct_reorder2(UF, factor(Variável, 2), Valor), y = Valor)) +
  
  geom_col(aes(fill = factor(UF), alpha = Variável), position = "identity") +
  
  scale_fill_manual(values = c("seagreen3", "seagreen3", "seagreen3",
                               "steelblue2","orange", rep("seagreen3", 12)),
                    guide = F) +
  
  scale_alpha_manual(values = c(0.5, 0.9)) +
  
  theme_minimal() +
  
  theme(axis.text.x = element_text(angle = 90,
                                   vjust = 0.5,
                                   hjust = 0.5,
                                   size = 11,
                                   face = "bold"),
        
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(linetype = "dashed", size = 1),
        panel.grid.minor.y = element_line(linetype = "dashed", size = 1),
        
        legend.position = "bottom") +
  
  labs(x = "", y = "", alpha = "") +
  
  geom_hline(yintercept = 0, size = 1) +
  
  geom_text(aes(label = Valor), position = position_dodge(0.9),
            vjust = ifelse(("Valor" <= -0.02), -1, -0.5)) +
  
  ylim(ifelse(refs$ref_min > 0, 0, refs$ref_min-0.5), refs$ref_max+0.5) +
  
  labs(title = "Índice Nacional de Preços ao Consumidor– INPC – Regiões",
       subtitle = "Variação mensal e acumulada no ano (%).",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.")

plot_graf_8 + p

```

```{r tabela_inpc_maiores, dpi = 300}

library(grid)
library(gridExtra)
library(gtable)

dados_tabela_2 <- sidrar::get_sidra(api = "/t/1100/n1/all/n7/all/n6/all/v/all/p/last%201/c315/all/d/v44%202,v45%204") %>%
 
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil, Região Metropolitana e Município`,
                Variável,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor) %>%
  
  dplyr::filter(UF == "Brasília - DF",
                Variável %in% c("INPC - Variação mensal", "INPC - Peso mensal"),
                stringr::str_detect(Item, stringr::regex("(\\d{7})"))) %>%
  
  tidyr::drop_na() %>%
  
  tidyr::spread(key = Variável, value = Valor) %>%
  
  dplyr::mutate(Contribuição = (`INPC - Variação mensal`)*(`INPC - Peso mensal`/100)) %>%
  
  dplyr::arrange(desc(Contribuição)) %>%
  
  dplyr::slice(c(1:5, (n()-4):n())) %>%
 
  dplyr::select(Item, Variação = `INPC - Variação mensal`, Peso = `INPC - Peso mensal`, Contribuição) %>%
  
  dplyr::mutate_at(vars(Variação:Contribuição), funs(round(., 2))) %>%
  
  dplyr::mutate(Item = stringr::str_remove(Item, "\\d+."))

tema <- ttheme_minimal(core=list(bg_params = list(fill = c(hsv(0.05, seq(1, 0.2, length.out = 5)),
                                                           hsv(0.35, seq(0.1, 0.5, length.out = 5))), col=NA)))

plot_tabela_2 <- tableGrob(dados_tabela_2, theme = tema, rows = NULL)

table <- plot_tabela_2

grid.newpage()

h <- grobHeight(table)
w <- grobWidth(table)

title <- textGrob("INPC - maiores e menores contribuições no mês - Brasília", 
                  y = unit(0.5,"npc") + 1*h, 
                  vjust = 0, gp = gpar(fontsize=10, fontface = "bold"))

footnote <- textGrob("Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN", 
                     x = unit(0.5,"npc") - 1*w,
                     y = unit(0.5,"npc") - 1*h, gp = gpar(fontsize = 7, fontface = "bold"))

gt <- gTree(children=gList(table, title, footnote))

grid.draw(gt)

```

```{r inpc_grupos_12m, fig.height=9, fig.width=13, dpi = 300}

dados_graf_9 <- sidrar::get_sidra(api = "/t/1100/n1/all/n6/5300108/v/2292/p/last%201/c315/7169,7170,7445,7486,7558,7625,7660,7712,7766,7786/d/v2292%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil e Município`,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor)

ordem <- dados_graf_9 %>%
  
  dplyr::filter(UF == "Brasília - DF", Item != "Índice geral") %>%
  
  dplyr::arrange(Valor) %>%
  
  dplyr::select(Item) %>%
  
  dplyr::mutate(Item = stringr::str_remove(Item, "\\d+."))

plot_graf_9 <- dados_graf_9 %>%
  
  dplyr::mutate(Item = stringr::str_remove(Item, "\\d+."),
                
                Item = factor(Item, levels = c(ordem$Item, "Índice geral"))) %>%
  
  ggplot(aes(y = Valor, x = Item, fill = UF)) +
  
  coord_flip() +
  
  geom_bar(stat = "identity", position = "dodge") + 
  
  theme_light() +
  
  labs(x = "", 
       y = "",
       fill = "") +
  
  theme(panel.grid.major.x = element_line(linetype = "dashed", size = 1),
        panel.grid.minor.x = element_line(linetype = "dashed", size = 1),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text.y = element_text(size = 14),
        
        legend.position = "bottom") +
  
  scale_fill_manual(values = c("dodgerblue2", "darkorange")) +
  
  geom_text(aes(label = Valor), 
            position = position_dodge(0.9),
            hjust = ifelse(("Valor" <= 0), -2, -0.2)) +
  
  labs(title = "INPC - Índice geral e grupos – Brasil e Brasília",
       subtitle = "Variação acumulada em 12 meses (%).",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.")

plot_graf_9 + p

```

```{r inpc_vs_ipca_ali_dom, fig.height=9, fig.width=13, dpi = 300}

source("C:\\Users\\36277\\Desktop\\acumular.R", encoding = "UTF-8")

ipca_ali_dom <- sidrar::get_sidra(api = "/t/1419/n6/5300108/v/63,66/p/all/c315/7171/d/v63%202,v66%204") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data, Variável, Valor) %>%
  
  tidyr::spread(key = Variável, value = Valor) %>%
  
  dplyr::mutate("IPCA" = (`IPCA - Variação mensal`*`IPCA - Peso mensal`)/100) %>%
  
  dplyr::mutate_at(vars(IPCA), funs(c(rep(NA, 11), acum(., n = 12))))

inpc_ali_dom <- sidrar::get_sidra(api = "/t/1100/n6/5300108/v/44,45/p/all/c315/7171/d/v44%202,v45%204") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data, Variável, Valor) %>%
  
  tidyr::spread(key = Variável, value = Valor) %>%
  
  dplyr::mutate("INPC" = (`INPC - Variação mensal`*`INPC - Peso mensal`)/100) %>%
  
  dplyr::mutate_at(vars(INPC), funs(c(rep(NA, 11), acum(., n = 12))))

ipca_inpc <- dplyr::inner_join(ipca_ali_dom, inpc_ali_dom) %>% 
  
  dplyr::select(Data, IPCA, INPC) %>% 
  
  tidyr::drop_na()


dados_graf_10 <- ipca_inpc %>%
  
  tidyr::gather(key = var, value = valor, -Data) %>%
  
  dplyr::filter(Data >= "2017-12-01") %>% 
  
  dplyr::group_by(var) %>%
  
  dplyr::mutate(label = ifelse(valor %in% tail(valor, 2), round(valor, 2), NA))
 

plot_graf_10 <- dados_graf_10 %>%
  
  ggplot(aes(x = Data, y = valor, color = var, label = label)) + 
  
  geom_line(lwd = 1.2) +
   
  theme_minimal() +
  
  theme(legend.position = "bottom", 
        
        legend.text = element_text(size = 11),
        
        axis.text.x = element_text(size = 11, angle = 45),
        axis.text.y = element_text(size = 11)) +
  
  labs(x = "", y = "", color = "") +
  
  labs(title = "Alimentação no domicílio: IPCA e INPC.",
       subtitle = "Contribuição em 12 meses (p.p)",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.") +
  
  scale_x_date(date_breaks = "1 month",
               labels = date_format("%b-%y")) +
  
  geom_label_repel(show.legend = F)
  
plot_graf_10 + p


```

```{r ipca_inpc_geral, fig.height=9, fig.width=13, dpi = 300}

source("C:\\Users\\36277\\Desktop\\acumular.R", encoding = "UTF-8")

ipca_geral <- sidrar::get_sidra(api = "/t/1419/n6/5300108/v/2265/p/all/c315/7169/d/v2265%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data, IPCA = Valor)

inpc_geral <- sidrar::get_sidra(api = "/t/1100/n6/5300108/v/2292/p/all/c315/7169/d/v2292%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data, INPC = Valor)

ipca_inpc_geral <- dplyr::inner_join(ipca_geral, inpc_geral) %>% 
  
  tidyr::drop_na()


dados_graf_11 <- ipca_inpc_geral %>%
  
  tidyr::gather(key = var, value = valor, -Data) %>%
  
  dplyr::filter(Data >= "2017-08-01") %>% 
  
  dplyr::group_by(var) %>%
  
  dplyr::mutate(label = ifelse(valor %in% tail(valor, 2), round(valor, 2), NA))
 

plot_graf_11 <- dados_graf_11 %>%
  
  dplyr::filter(Data >= "2017-12-01") %>%
  
  ggplot(aes(x = Data, y = valor, color = var, label = label)) + 
  
  geom_line(lwd = 1.2) +
   
  theme_minimal() +
  
  theme(legend.position = "bottom", 
        
        legend.text = element_text(size = 11),
        
        axis.text.x = element_text(size = 11, angle = 45),
        axis.text.y = element_text(size = 11)) +
  
  labs(x = "", y = "", color = "") +
  
  labs(title = "IPCA e INPC.",
       subtitle = "Variação acumulada em 12 meses (p.p)",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.") +
  
  scale_x_date(date_breaks = "1 month",
               labels = date_format("%b-%y")) +
  
  geom_label_repel(show.legend = F)
  
plot_graf_11 + p



```

```{r ipca_aluguel, fig.height=9, fig.width=13, dpi = 300}

dados_graf_12 <- sidrar::get_sidra(api = "/t/1419/n1/all/n6/5300108/v/2265/p/all/c315/7448/d/v2265%202") %>%
  
  dplyr::mutate(Data = paste(`Mês (Código)`, "01", sep = "") %>% lubridate::ymd()) %>%
  
  dplyr::select(Data,
                UF = `Brasil e Município`,
                Item = `Geral, grupo, subgrupo, item e subitem`,
                Valor) %>%
  
  dplyr::group_by(UF) %>%
  
  dplyr::mutate(label = ifelse(Valor %in% tail(Valor, 2), round(Valor, 2), NA))

plot_graf_12 <- dados_graf_12 %>%
  
  dplyr::filter(Data >= "2012-02-01") %>%
  
  ggplot(aes(x = Data, y = Valor, color = UF, label = label)) + 
  
  geom_line(lwd = 1.2) +
  
  scale_color_manual(values = c("steelblue2", "orange")) +
   
  theme_minimal() +
  
  theme(legend.position = "bottom", 
        
        legend.text = element_text(size = 11),
        
        axis.text.x = element_text(size = 11),
        axis.text.y = element_text(size = 11)) +
        
        #panel.grid.major.x = element_blank(),
        #panel.grid.minor.x = element_blank(),
        
        #panel.grid.major.y = element_line(linetype = "dashed", size = 0.5),
        #panel.grid.minor.y = element_line(linetype = "dashed", size = 0.5)) +
  
  labs(x = "", y = "", color = "") +
  
  labs(title = "IPCA – Aluguel residencial – Brasil e Brasília.",
       subtitle = "Variação acumulada em 12 meses (%).",
       caption = "Fonte: IBGE. Elaboração: DIEPS-Gecon/CODEPLAN.") +
  
  scale_x_date(date_breaks = "7 month",
               labels = date_format("%b-%y"), limits = as.Date(c("2012-12-01", "2019-07-01"))) +
  
  geom_label_repel(show.legend = F)
  
plot_graf_12 + p


```